FROM nginx

# add some nice to have tools to the container
RUN apt-get update
RUN apt-get install iputils-ping -y
RUN apt-get install nano -y

# create  directory for cache storage
RUN mkdir -p /var/cache/nginx

# copy configs from this folder
COPY etc /etc